apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps-lab3
  namespace: apps-caculator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apps-lab3
  template:
    metadata:
      labels:
        app: apps-lab3
    spec:
      containers:
      - name: apps-lab3
        image: registry-nexus.cloud/apps1
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: admin-repo
---
apiVersion: v1
kind: Service
metadata:
  name: svc-lab3
  namespace: apps-caculator
spec:
  selector:
    app: apps-lab3
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
